# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4e26af177eb93ed5015d59662aaa0c05c906bdba9ca4e44cd4eec9db57b76e279fd70c5c398998bbc8838596425e017edf2fe1600f0c448e199026ab63d2b9f

test:
  secret_key_base: ba732157d9a0b76e0ce5eb7822e6d90e3dfd8d32a59d324dc8b079d2784d2b3107a864f1516cf8a30f82e11485c2cfce8429fb3a8e1567fa90926a091fbb0c18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
